version: '3'
services:
  build-bin:
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - ./:/home/Projects/
    working_dir: /home/Projects/
    entrypoint:
            # - /bin/bash
      - docker/entrypoint.sh
